### ISSUE TITLE
retconSrcset rendering all images at the largest defined size

### ISSUE THREAD

**Issue by garycrane** [mmikkel/Retcon-Craft#48] opened 2022-12-15 21:06 UTC
I'm trying to output a srcset on images within my Redactor field and I can't seem to get it to transform each of the sizes. It seems to be transforming the image 3 times, each to the size of the largest size in my srcset.

I'm using the following code: 

```
{{ entry.body|retconSrcset(
    [
        {width: 375},
        {width: 480},
        {width: 768}
    ],
    'img',
    '(min-width: 40em) 80vw, 100vw'
) }}
```

It's rendering an image tag as follows (I've changed the names to highlight the issue):

```
<img src="768-wide.png" alt="My Image" srcset="768-wide.png 375w, 768-wide.png 480w, 768-wide.png 768w" sizes="(min-width: 40em) 80vw, 100vw">
```

I was expecting: 

```
<img src="768-wide.png" alt="My Image" srcset="375-wide.png 375w, 480-wide.png 480w, 768-wide.png 768w" sizes="(min-width: 40em) 80vw, 100vw">
```

Hope this makes sense? Any ideas what might be going on? Any help/guidance would be greatly appreciated.

**Comment by mmikkel** [comment] 2022-12-16 07:29
I just tested your code snippet on a Redactor field containing a single image, and it worked as expected. Not sure what would cause 3 identical sizes in your `srcset`.

What are you using to transform the images? Craft or the Imager plugin? What are the dimensions for the original image?

Any chance you could include the actual source being output as well?

**Comment by garycrane** [comment] 2022-12-16 08:04
Thanks for your prompt response. I'm using imager, as the images are being hosted as Servd assets. Now that I've come to this fresh in the morning, I think the issue is to do with my config and using Servd assets. 

Here is the output (I've obscured the project name):

```
<img src="https://cdn2.assets-servd.host/project/local/assets/features-2.png" data-image="39803" alt="Live Chart" srcset="/imager/cdn2_assets-servd_host/project/local/assets/features-2_49990baf5f379ea76cbf8b3ae6f9c9c8.png 375w, /imager/cdn2_assets-servd_host/project/local/assets/features-2_b12650c5e7f047954b67d3ceb0a0b1c3.png 480w, /imager/cdn2_assets-servd_host/project/local/assets/features-2_8877a1e41a9899e9d1bb1f264f777a6f.png 768w" sizes="(min-width: 40em) 80vw, 100vw">
```

The fact that the srcset URLs are starting with /imager/ is the giveaway. I think I'll reach out to Servd to see if they can help. I've tried a few different config settings but nothing is working as expected.

Have you seen anything similar before?

**Comment by mmikkel** [comment] 2022-12-16 08:16
Thanks for the additional info @garycrane. To be sure, I just tested your snippet with Imager installed, and on my end I still get three different images at 375px, 480px and 768px as expected.

From your source, the actual images are obviously different files – i.e. Imager is creating three different transforms. If these images have the same size/dimensions, something is wrong somewhere, but I don't think it's likely that the issue is with Retcon.

Going to close this for the time being, but happy to re-open if more info surfaces :)

**Closed by mmikkel** 2022-12-16 08:16 UTC
