### ISSUE TITLE
retconSrcset is encoding <p> tags

### ISSUE THREAD

**Issue by codecreate** [mmikkel/Retcon-Craft#2] opened 2018-07-19 06:52 UTC
I am using the retconSrcset method to modify image tags that come from a redactor field in a Craft 3 matrix but paragraph and a tags are being encoded to html entities.

Any ideas on a resolution or is it a bug?

**Comment by mmikkel** [comment] 2018-07-19 07:05
Hi @codecreate – which version of Retcon are you using?

**Comment by mmikkel** [comment] 2018-07-19 07:16
Nevermind, bug confirmed. Thank you for reporting, I'll get it sorted ASAP.

**Comment by codecreate** [comment] 2018-07-19 07:41
Thanks. Looking to launch this project in the next couple of days so I'll stay tuned.

**Comment by mmikkel** [comment] 2018-07-19 07:50
@codecreate This issue should be resolved in [v. 2.0.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.1).

**Closed by mmikkel** 2018-07-19 07:50 UTC
Labels: bug

**Comment by codecreate** [comment] 2018-07-25 07:43
Hi,

The srcset tag is not being created at all now. Craft and Retcon are both up to date.

Thanks

Andy

**Comment by mmikkel** [comment] 2018-07-25 08:20
Hi @codecreate, I assume you're using the "catch-all" filter `retcon` – I identified an issue with that and the `srcset` method.

The "standalone" `retconSrcset` filter seems to work as it should; will issue a fix for the `retcon` filter ASAP.

**Comment by codecreate** [comment] 2018-07-25 08:29
Yes. Using the srcset method. It was working before you fixed the other issue but I only noted that it wasn't working at all during some uat today.

Thanks.



On 25 July 2018 6:20:49 pm AEST, "M. Mikkel Rummelhoff" <notifications@github.com> wrote:
>Hi @codecreate, I assume you're using the "catch-all" filter `retcon` –
>I identified an issue with that and the `srcset` method.
>
>The "standalone" `retconSrcset` filter seems to work as it should; will
>issue a fix for the `retcon` filter ASAP.
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mmikkel/Retcon-Craft/issues/2#issuecomment-407674100

----------
Sent from the mobile office of Code Create

**Comment by mmikkel** [comment] 2018-07-25 08:32
Yeah, it's actually not an issue with the `srcset` method; it's a regression error in the `retcon` method that was introduced in the 2.0.3 update. I should have a fix up shortly; if it's critical you can use the `retconSrcset` filter directly, for now.

**Comment by codecreate** [comment] 2018-07-25 08:43
Totally awesome. I've left work for the day so not an issue, at least until tomorrow and I can change to the other method if I need to.

Thanks. 

On 25 July 2018 6:32:08 pm AEST, "M. Mikkel Rummelhoff" <notifications@github.com> wrote:
>Yeah, it's actually not an issue with the `srcset` method; it's a
>regression error in the `retcon` method that was introduced in the
>2.0.3 update. I should have a fix up shortly; if it's critical you can
>use the `retconSrcset` filter directly, for now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mmikkel/Retcon-Craft/issues/2#issuecomment-407677307

----------
Sent from the mobile office of Code Create

**Comment by mmikkel** [comment] 2018-07-25 08:52
The issue should be resolved in [the 2.0.4 release](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.4).

**Comment by codecreate** [comment] 2018-07-25 23:18
Updated this morning and not seeing the srcset output using the retconSrcset filter

`
{{ block.itemContent|retconSrcset(
							[
							    'inlineSmall',
							    {width: 848},
							    'inlineLarge',
							    {width: 414}
							]
						) }}
`
Standard img tags are being printed
`<figure><img src="http://www.lemonade.com.au/staging/public_html/uploads/FPV_14.jpg" alt=""><figcaption>Orange is a tough colour to get past contrast testing.</figcaption></figure>`

**Comment by mmikkel** [comment] 2018-07-25 23:30
Hm, not able to reproduce this @codecreate. Just tested with identical code to yours + using the `retcon` filter, both with and without Imager installed, and everything works on my end.

1. Do you have `devMode` turned on?
2. Are you sure your template isn't cached?
3. Your `src` attribute looks a bit odd – do you have a folder called `public_html` below your public web root? Does the image actually load in the frontend?

**Comment by mmikkel** [comment] 2018-07-25 23:36
Also, please test the `retconTransform` filter, just to see if that works for you:

`{{ block.itemContent|retconTransform( 'inlineSmall' ) }}`

**Comment by codecreate** [comment] 2018-07-25 23:42
Everything loads perfectly. Just not parsed into the srcset tags. Redactor version 2.1.3 and Retcon 2.0.4

All cache cleared.

**Comment by codecreate** [comment] 2018-07-25 23:45
The retconTransform filter returns nothing at all. No content from block.itemContent what so ever.

**Comment by mmikkel** [comment] 2018-07-25 23:47
That's... weird. Do you have [`devMode`](https://docs.craftcms.com/v2/config-settings.html#general) turned on?

**Comment by mmikkel** [comment] 2018-07-25 23:51
I assume that the image filters aren't working because Retcon isn't able to locate your images. What are the values for your Asset Volume's `Base URL` and `File System Path` settings?

**Comment by mmikkel** [comment] 2018-07-25 23:52
The `retconTransform` filter returning nothing is very odd, though. There's nothing in the code that should make it return an empty string, e.g. if no images are found or it isn't able to transform anything. Might be a different/another bug, will investigate.

**Comment by codecreate** [comment] 2018-07-25 23:52
DevMode was on but tested off with the same result. Images are displayed normally without the filter so I don't know that it can be the path.

**Comment by codecreate** [comment] 2018-07-25 23:53
All the text is returned normally.

**Comment by mmikkel** [comment] 2018-07-25 23:55
It can be, because Retcon just deduces the filepath based on the URL found in the `src` attribute – i.e. if your image URL is `/public_html/uploads/foobar.jpg`, it will look for the image in `@webroot/public_html/`.

**Comment by mmikkel** [comment] 2018-07-25 23:58
Hah, I found the bug in `retconTransform` that results in the method returning nothing at all if it isn't able to transform the image. Good call, thanks for drawing my attention to it...

**Comment by mmikkel** [comment] 2018-07-25 23:59
Just occurred to me – is your Asset Volume local or remote (S3 or the like)?

**Comment by codecreate** [comment] 2018-07-26 00:00
Excellent stuff. Hope that's easy to resolve.

**Comment by mmikkel** [comment] 2018-07-26 00:01
Yeah, I already put up a fix in [20ec399](https://github.com/mmikkel/Retcon-Craft/commit/20ec399c1c9383cc82fb90268e3f55aa5b181f0b), will cut a new patch release later.

**Comment by codecreate** [comment] 2018-07-26 00:13
OK. Images are now returned but without srcset. My local version returns the srcset ok. Any ideas?

**Comment by codecreate** [comment] 2018-07-26 00:14
Probably just the path, right?

**Comment by mmikkel** [comment] 2018-07-26 00:15
That depends! 

What are the values for your Asset Volume's `Base URL` and `File System Path` settings?

Also, do you have the Imager plugin installed?

**Comment by codecreate** [comment] 2018-07-26 00:16
@web/uploads

@webroot/uploads

Not using imager

**Comment by codecreate** [comment] 2018-07-26 00:18
Transforms outside of redactor, not using Retcon are all found and display fine.

**Comment by mmikkel** [comment] 2018-07-26 00:30
Those settings should normally be good.

I just pushed a commit adding some additional exceptions to the image transform function. If you don't mind helping me out, could you `composer require mmikkel/retcon:dev-master`, make sure `devMode` is on, and report back if you're seeing any exceptions in the front end?

(Might also need to put [`"minimum-stability": "dev"`](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your `composer.json` file to install directly from `master` – you can remove it later, of course).

**Comment by codecreate** [comment] 2018-07-26 00:42
Will do that now.

**Comment by codecreate** [comment] 2018-07-26 00:50
Done. No exceptions.

**Comment by mmikkel** [comment] 2018-07-26 00:59
Hm, and devMode is enabled?

**Comment by codecreate** [comment] 2018-07-26 01:05
Ah, nope. Hadn't turned on devMode on staging

`yii\base\Exception: Image /hsphere/local/home/lemphp/lemonade.com.au/staging/public_html//staging/public_html/uploads/RMBL_13.jpg not found in /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/mmikkel/retcon/src/library/RetconHelper.php:183
Stack trace:
#0 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/mmikkel/retcon/src/services/RetconService.php(195): mmikkel\retcon\library\RetconHelper::getTransformedImage('http://www.lemo...', Object(craft\models\AssetTransform), Array, Array)
#1 [internal function]: mmikkel\retcon\services\RetconService->mmikkel\retcon\services\{closure}(Array, Object(craft\models\AssetTransform))
#2 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/mmikkel/retcon/src/services/RetconService.php(199): array_reduce(Array, Object(Closure), Array)
#3 /hsphere/local/home/lemphp/lemonade.com.au/staging/storage/runtime/compiled_templates/ff/fff347c86b29a4e0b25a4873cffdb23d346879d570693a752a6b6d55a605fd94.php(143): mmikkel\retcon\services\RetconService->srcset('<p>We jumped st...', Array)
#4 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_7966bda2403071d3a702c1525f5d64aed9f37008e646f24789c2d72827641254->block_content(Array, Array)
#5 /hsphere/local/home/lemphp/lemonade.com.au/staging/storage/runtime/compiled_templates/0d/0dc17adb63eb090db8a130bc548e7d80f850518ca1528d258b106cdf1d16eb33.php(194): Twig_Template->displayBlock('content', Array, Array)
#6 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_3cf2aebf3461ef4d459405a9e8aaaba59b4a50301ad144407cadee832374338a->block_layoutContent(Array, Array)
#7 /hsphere/local/home/lemphp/lemonade.com.au/staging/storage/runtime/compiled_templates/f9/f96eb57d7929908898d932335eefa89307d9150ae5f70c2aa244d6094daec941.php(120): Twig_Template->displayBlock('layoutContent', Array, Array)
#8 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_53ef49178c8ad5184e92497b55c64ea91a9d2f4020807cda186948d8a3bdd1c6->doDisplay(Array, Array)
#9 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#10 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#12 /hsphere/local/home/lemphp/lemonade.com.au/staging/storage/runtime/compiled_templates/0d/0dc17adb63eb090db8a130bc548e7d80f850518ca1528d258b106cdf1d16eb33.php(30): craft\web\twig\Template->display(Array, Array)
#13 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_3cf2aebf3461ef4d459405a9e8aaaba59b4a50301ad144407cadee832374338a->doDisplay(Array, Array)
#14 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /hsphere/local/home/lemphp/lemonade.com.au/staging/storage/runtime/compiled_templates/ff/fff347c86b29a4e0b25a4873cffdb23d346879d570693a752a6b6d55a605fd94.php(28): craft\web\twig\Template->display(Array, Array)
#18 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_7966bda2403071d3a702c1525f5d64aed9f37008e646f24789c2d72827641254->doDisplay(Array, Array)
#19 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#23 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#24 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('work/_entry', Array)
#25 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate('work/_entry', Array)
#26 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('work/_entry', Array)
#27 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('work/_entry', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('work/_entry', Array)
#29 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('render', Array)
#32 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#33 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#34 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#35 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /hsphere/local/home/lemphp/lemonade.com.au/staging/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /hsphere/local/home/lemphp/lemonade.com.au/staging/public_html/index.php(21): yii\base\Application->run()
#38 {main}`

**Comment by mmikkel** [comment] 2018-07-26 01:09
Cool, it’s what I expected; a path issue. It’s nighttime here, but I’ll take a stab at it tomorrow and try to figure out where it goes wrong. Thanks for the help so far!

**Comment by codecreate** [comment] 2018-07-26 01:11
Thanks for everything.

**Comment by mmikkel** [comment] 2018-07-26 09:12
@codecreate I pushed a new commit – it'd be great if you'd do a `composer update mmikkel/retcon`, and let me know how it works.

**Comment by codecreate** [comment] 2018-07-26 09:14
I'll do it in the morning. Probably about 14 hrs from now.



On 26 July 2018 7:12:41 pm AEST, "M. Mikkel Rummelhoff" <notifications@github.com> wrote:
>@codecreate I pushed a new commit – it'd be great if you'd do a
>`composer update mmikkel/retcon`, and let me know how it works.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mmikkel/Retcon-Craft/issues/2#issuecomment-408032119

----------
Sent from the mobile office of Code Create

**Comment by codecreate** [comment] 2018-07-26 22:56
Composer says there's nothing to update

**Comment by mmikkel** [comment] 2018-07-27 17:51
@codecreate That's odd. Can you confirm that you have `"mmikkel/retcon": "dev-master"` in your `composer.json`, and not `"mmikkel/retcon": "^2.0"`? Also make sure that you've got `"minimum-stability": "dev"` in there.

You might also try `composer update mmikkel/retcon:dev-master`, but it shouldn't be necessary. 

In any case, if Composer says there's nothing to update, and you're definitely pulling `dev-master` and not a release, you should be on the latest commit. You can confirm if you are by opening the file `/vendor/mmikkel/retcon/src/library/RetconHelper.php`, and [diff it](https://www.diffchecker.com/) with [the latest version in the repo](https://raw.githubusercontent.com/mmikkel/Retcon-Craft/master/src/library/RetconHelper.php).

In any case, once you're on the latest commit, give the `retconSrcset` filter another go and let me know if it works for you now or not. Thanks!

**Comment by mmikkel** [comment] 2018-07-28 10:57
FWIW; I've cut a release for the latest commits now, because I wanted to make the bug fix for `retconTransform` available: https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.5
